-   id: google-style-java
    name: Google Java Code Style for Java
    description: Formats code in Google's Java codestyle.
    entry: ./format-code.sh
    language: script
    files: \.java$ # We don't technically need this, as the script will filter for us, but this will allow the hook to be skipped if no Java is changed.

